[world]
description = "jokers_of_neon_classic"
name = "jokers_of_neon_classic"
seed = "jokers_of_neon_classic"

[namespace]
default = "kitties_of_neon"

[env]
rpc_url = "https://api.cartridge.gg/x/jokers-mods/katana"
account_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"
